### ISSUE TITLE
Invalid fallback style "LVM

### ISSUE THREAD

**Issue by Thalhammer** [RafikFarhad/clang-format-github-action#1]
I get the following error message for each of my files:
"Invalid fallback style "LVM"
I think this is caused by  https://github.com/RafikFarhad/clang-format-github-action/blob/d93d8bf27c6d7f9f3ede3aa877497684aac34dc7/entrypoint.sh#L41
"--fallback-style=LVM" should be "--fallback-style=LLVM"

**Comment by RafikFarhad** [comment]
Hi @Thalhammer , this issue has been fixed in `v1.0.1`. 
Thanks for pointing this out. 
Cheers 🍻
