### ISSUE TITLE
Actions encounters error if excludes is not defined.

### ISSUE THREAD

**Issue by Miniland1333** [RafikFarhad/clang-format-github-action#7]
When attempting to use this action, the error ```/entrypoint.sh: line 44: local: `': not a valid identifier``` occurs.

My guess is that for the following line of code, having the default excludes="" causes `find_cmd` to have only two arguments and thus results in this error. I can confirm that if I instead set excludes="some_file.cpp", then the code works as expected.
https://github.com/RafikFarhad/clang-format-github-action/blob/0061b39593fe96f861c3aefcf1aff084d42744e1/entrypoint.sh#L70

My guess for a fix would be to either modify line 44 so that it is able to treat an empty string as the second argument, or somehow change the default option for excludes.

Additionally, I would recommend documenting the `excludes` option in the README.

Thank you for looking into this issue.

**Comment by RafikFarhad** [comment]
Thank you for reporting.
Could you please create a PR? 
I do not have the setup to test this at the moment and will require to wait until the weekend.

**Comment by kadler** [comment]
I ran in to this too and made a PR

**Comment by RafikFarhad** [comment]
@Miniland1333 Try release [3.1](https://github.com/RafikFarhad/clang-format-github-action/releases/tag/3.1)

**Comment by Miniland1333** [comment]
Just ran the updated version right now. It looks like the script is still throwing the warning ``/entrypoint.sh: line 44: local: `': not a valid identifier`` and causes the code to not find my files.


![image](https://github.com/RafikFarhad/clang-format-github-action/assets/12994749/3a647ace-f39a-4e46-9e2a-6f45f6cdb4bc)

![image](https://github.com/RafikFarhad/clang-format-github-action/assets/12994749/97c75bcd-6121-4342-85ad-9fbca6864943)

As before, only if I explicitly define excludes does the code find my files and thus function properly:
![image](https://github.com/RafikFarhad/clang-format-github-action/assets/12994749/00351169-7792-4ec2-adc7-ae0a413cd86e)

Therefore, at least on my end it appears that unfortunately v3.1 does not address the observed issue.

**Comment by RafikFarhad** [comment]
Sorry to hear that; let me explore it.

**Comment by RafikFarhad** [comment]
@Miniland1333 Can you please try v3.2?

**Comment by Miniland1333** [comment]
@RafikFarhad with version 3.2 it now looks like it is behaving properly when exclude is not defined!

![image](https://github.com/RafikFarhad/clang-format-github-action/assets/12994749/be50f7ee-5879-442f-bf90-a51242b4b92c)
![image](https://github.com/RafikFarhad/clang-format-github-action/assets/12994749/f7670e9b-fbdb-4f14-8d59-0884b5c348da)

Thanks so much for addressing this issue! I think it is finally solved. Closed by #10
